fork: main_fork_ex
	./main_fork_ex
getpid: main_getpid_ex
	./main_getpid_ex
main_fork_ex: main_fork.c
	gcc -o main_fork_ex main_fork.c
main_getpid_ex: main_getpid.c
	gcc -o main_getpid_ex main_getpid.c
clean:
	rm -r *_ex
